eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  rabbitmq:
    host: 101.132.106.160
    port: 5672
    username: admin
    password: '{cipher}3f7be53206c72d5e3eba3215ee9c9755d0cfd2816360b767eec95546abf59855'
    virtual-host: my_vhost
  datasource:
    url: jdbc:mysql://101.132.106.160:3306/busi?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: '{cipher}efd234427de7b39deb23fc7090b1d58746c8a5867f0ed24147d15c6b4cadc957'
  redis:
    #redis机器ip
    hostname: 101.132.106.160
    #redis端口
    port: 6379
    #redis密码
    password: '{cipher}06a5083caf5b79359382b5c4f752e67dbceb341a17dbd2b97420f34d8f811071'
    #redis超时时间（毫秒），如果不设置，取默认值2000
    timeout: 10000
    #最大空闲数
    maxIdle: 300
    #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
    #maxActive=600
    #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
    maxTotal: 1000
    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    maxWaitMillis: 1000
    #连接的最小空闲时间 默认1800000毫秒(30分钟)
    minEvictableIdleTimeMillis: 30000
    #每次释放连接的最大数目,默认3
    numTestsPerEvictionRun: 3
    #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    timeBetweenEvictionRunsMillis: 30000
    #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
    #在空闲时检查有效性, 默认false
    testWhileIdle: true
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.1.73:9300
      repositories:
        enabled: true # Whether to enable Elasticsearch repositories.

redisson:
  address: 101.132.106.160
  port: 6379
  password: '{cipher}06a5083caf5b79359382b5c4f752e67dbceb341a17dbd2b97420f34d8f811071'
  releaseTime: 8000

swagger:
  groupName: sihai
  pathMapping: /
  title: sihai
  description: sihai
  version: 1
  termsOfServiceurl: 1
  license: 1
  licenseurl: 1

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logstash:
  dest: 192.168.1.73:4567

logging:
  config: classpath:logback-custom.xml
  level:
    ROOT: INFO