eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  rabbitmq:
    host: 101.132.106.160
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
