eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: work.sihai.app.busi
  global-config:
    db-config:
      field-strategy: not_empty
      id-type: auto
      db-type: mysql
    banner: false

spring:
  rabbitmq:
    host: 101.132.106.160
    port: 5672
    username: admin
    password: '{cipher}3f7be53206c72d5e3eba3215ee9c9755d0cfd2816360b767eec95546abf59855'
    virtual-host: my_vhost
  datasource:
    url: jdbc:mysql://101.132.106.160:3306/busi?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: Mlvrs520@
  redis:
    #redis机器ip
    hostname: 101.132.106.160
    #redis端口
    port: 6379
    #redis密码
    password: '{cipher}06a5083caf5b79359382b5c4f752e67dbceb341a17dbd2b97420f34d8f811071'
    #redis超时时间（毫秒），如果不设置，取默认值2000
    timeout: 10000
    #最大空闲数
    maxIdle: 300
    #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
    #maxActive=600
    #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
    maxTotal: 1000
    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    maxWaitMillis: 1000
    #连接的最小空闲时间 默认1800000毫秒(30分钟)
    minEvictableIdleTimeMillis: 30000
    #每次释放连接的最大数目,默认3
    numTestsPerEvictionRun: 3
    #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    timeBetweenEvictionRunsMillis: 30000
    #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
    #在空闲时检查有效性, 默认false
    testWhileIdle: true